// Ambient declarations for non-code assets imported for their side effects.
//
// TypeScript 6 tightened side-effect imports (TS2882: "Cannot find module or type declarations for
// side-effect import"): `import "./globals.css"` now needs a declaration, where TS 5 let it pass.
// The bundler (Next/Turbopack for the app, Vite for driver.js's stylesheet) resolves these — the
// type system just needs to know they exist. Declared here rather than in next-env.d.ts, which is
// generated by Next and must not be edited.
declare module "*.css";
